#ifndef NETSEC_NETWORK_PROTOCOLENUM_HH_
#define NETSEC_NETWORK_PROTOCOLENUM_HH_

namespace NETSEC_NETWORK {
  enum class ProtocolEnum : int {
    ETHERNET, ARP, TCP, UDP, DNS, HTTP
  };
}

#endif /* !NETSEC_NETWORK_PROTOCOLENUM_HH_ */
