#ifndef PROTOCOLENUM_H
#define PROTOCOLENUM_H

#include <unordered_map>

enum class ProtocolEnum : int {
    UNKNOWN,//IDENTIFIE ANALYSE
    ETHERNET, //IDENTIFIE ANALYSE
    ARP,//IDENTIFIE ANALYSE
    IP, //IDENTIFIE
    ICMP, //IDENTIFIE
    TCP, //IDENTIFIE
    UDP, //IDENTIFIE
    HTTP, //IDENTIFIE
    DNS //IDENTIFIE
};

#endif // PROTOCOLENUM_H
